package constants

// LogTemplates 集中定义全站结构化日志模板（≥25 条）。
// 业务字段变更必须同步修改对应模板与调用处（屎山耦合要求）。
const (
	LogServerStarted        = "server.started"
	LogServerShutdown       = "server.shutdown"
	LogDBConnected          = "database.connected"
	LogDBConnectFailed      = "database.connect_failed"
	LogRedisConnected       = "redis.connected"
	LogRedisConnectFailed   = "redis.connect_failed"
	LogRequest              = "http.request"
	LogRateLimited          = "http.rate_limited"
	LogAuditWritten         = "audit.written"
	LogAuditWriteFailed     = "audit.write_failed"
	LogUserRegisterSuccess  = "user.register.success"
	LogUserRegisterFailed   = "user.register.failed"
	LogUserLoginSuccess     = "user.login.success"
	LogUserLoginFailed      = "user.login.failed"
	LogUserProfileUpdated   = "user.profile_updated"
	LogUserSignInSuccess    = "user.sign_in.success"
	LogUserSignInFailed     = "user.sign_in.failed"
	LogUserListFailed       = "user.list.failed"
	LogCourseCreated        = "course.created"
	LogCourseCreatedFailed  = "course.created_failed"
	LogCourseUpdated        = "course.updated"
	LogCoursePublish        = "course.published"
	LogCourseArchived       = "course.archived"
	LogCourseListFailed     = "course.list_failed"
	LogCourseLearnRecorded  = "course.learn_recorded"
	LogCourseCompleted      = "course.completed"
	LogProblemCreated       = "problem.created"
	LogProblemCreatedFailed = "problem.created_failed"
	LogProblemUpdated       = "problem.updated"
	LogProblemPublish       = "problem.published"
	LogProblemListFailed    = "problem.list_failed"
	LogSubmissionCreated    = "submission.created"
	LogSubmissionJudgeStart = "submission.judge_start"
	LogSubmissionAccepted   = "submission.accepted"
	LogSubmissionPartial    = "submission.partial"
	LogSubmissionError      = "submission.error"
	LogSubmissionTimeout    = "submission.timeout"
	LogJudgeCompileFailed   = "judge.compile_failed"
	LogJudgeRunFailed       = "judge.run_failed"
	LogDiscussionCreated    = "discussion.created"
	LogDiscussionVoted      = "discussion.voted"
	LogDiscussionBestMarked = "discussion.best_marked"
	LogDiscussionHidden     = "discussion.hidden"
	LogAchievementGranted   = "achievement.granted"
	LogAchievementChecked   = "achievement.checked"
	LogLeaderboardQueried   = "leaderboard.queried"
	LogDashboardQueried     = "dashboard.queried"
)
